- name: Install Maven
  unarchive:  
    src: http://www-us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
    dest: /opt
    remote_src: yes
- name: JAVA_HOME environment variable
  blockinfile:
    dest: /etc/profile
    block: |
      M2_HOME=/opt/apache-maven-3.5.4
      PATH=$PATH:$M2_HOME/bin
      export M2_HOME
      export PATH
    backup: yes      
- name: OwnerShip
  file:
    path: /opt/apache-maven-3.5.4
    owner: root
    group: root
- name: symbolic link pointing to the original Apache Maven 3.5 directory
  file:
    src: /opt/apache-maven-3.5.4
    dest: /opt/apache-maven
    state: link
