---
- hosts: tom
  become: yes
  vars:
    req_java: "java-1.8.0-openjdk"
    set_java: "jre-1.8.0-openjdk"
    req_tomcat_version: 9.0.27
    tomcat_port: 8090
    tomcat_url: http://www-us.apache.org/dist/tomcat/tomcat-{{req_tomcat_version.split('.')[0]}}/v{{req_tomcat_version}}/bin/apache-tomcat-{{req_tomcat_version}}.tar.gz
  tasks:
    - name: update repos
      yum:
        name: "*"
        state: latest
      tags:
        - update
    - name: Install required java
      yum:
        name: "{{req_java}}"
        state: present
      tags:
        - java  
    - name: Setting java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{set_java}}/bin/java
      tags:
        - Setting_java
    - name: Download required tomcat
      get_url:
        url: "{{tomcat_url}}"
        dest: /usr/local
      tags:
        - tom_url
    - name: Exactrating the tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-{{req_tomcat_version}}.tar.gz"
        dest: /usr/local
        remote_src: yes 
    - name: tomcat home
      stat: path=/usr/local/apache-tomcat-{{req_tomcat_version}}
      register: tomcat_home
    - name: renaming tomcat home
      command: mv /usr/local/apache-tomcat-{{req_tomcat_version}} //usr/local/latest
      when: tomcat_home.stat.exists
    - name: Starting tomcat
      shell: nohup /usr/local/latest/bin/startup.sh &
      tags:
        - starting_tomcat
    - name: Stoping tomcat 
      shell: nohup /usr/local/latest/bin/shutdown.sh &
      tags:
        - stoping tomcat
    - name: replace the tomcat port
      template:
        src: server.xml.j2
        dest: /usr/local/latest/conf/server.xml
    - name: copy context.xml files
      copy:
        src: context.xml
        dest: /usr/local/latest/webapps/host-manager/META-INF/context.xml
    - name: copy context.xml to other location
      copy:
        src: context.xml
        dest: /usr/local/latest/webapps/manager/META-INF/context.xml
    - name : tomcat users
      copy:
        src: tomcat-users.xml
        dest: /usr/local/latest/conf/tomcat-users.xml    
                  

