---
- hosts: tom
  become: yes
  vars:
    req_java: "java-1.8.0-openjdk"
    set_java: "jre-1.8.0-openjdk"
    req_tomcat_version: 9.0.27
    tomcat_port: 8090
    tomcat_url: http://www-us.apache.org/dist/tomcat/tomcat-{{req_tomcat_version.split('.')[0]}}/v{{req_tomcat_version}}/bin/apache-tomcat-{{req_tomcat_version}}.tar.gz
  tasks:
    
    

