- name : Install Java
  package:
    name: java
    state: present
- name : Ensure tomcat group exists
  group:
    name: tomcat
    state: present
- name: Ensure tomcat user exists
  user:
    name: tomcat
    shell: /bin/false
    groups: tomcat
    append: yes
    createhome: yes
    home: /opt/tomcat
- name : Install tomcat
  unarchive:
    src: http://apache.mirrors.ionfish.org/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz
    dest: /opt/tomcat
    remote_src: yes
  tags:
    - tomcat_install
- name: tomcat group ownership 
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes
- name: Configure Tomcat Web Management Interface
  copy:
    src: tomcat_users.xml
    dest: /opt/tomcat/apache-tomcat-8.5.39/conf/tomcat-users.xml
- name: change the IP address restrictions
  copy:
    src: context.xml
    dest: /opt/tomcat/apache-tomcat-8.5.39/webapps/host-manager/META-INF/context.xml
- name: Change Ip address restriction in other location
  copy:
    src: context.xml
    dest: /opt/tomcat/apache-tomcat-8.5.39/webapps/manager/META-INF/context.xmla
- name: start tomcat
  command: nohup /opt/tomcat/apache-tomcat-8.5.39/bin/startup.sh
  