---
# tasks file for jenk
- name: Updating repos
  package:
    name: "*"
    state: latest
- name: Install Java
  package:
    name: "{{ req_java}}"
    state: present
- name: Set Java_Home path
  shell: echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:/bin/java::")" | sudo tee -a /etc/profile
- name: Source /etc/profile
  shell: source /etc/profile
  register: output
  args:
    executable: /bin/bash
- debug: msg="{{ output }}"
