---
- hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning

  vars:
    instance_type: t2.micro
    security_group: webservers
    image: ami-0b500ef59d8335eee
    region: us-east-2
    keypair: key
    count: 1
  tasks:
    - name : Creating a new security group
      local_action:
        module: ec2_group
        name: "{{security_group }}"
        description: Security Group for newly created group
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    
    - name: Launch Ec2 t2.micro
      local_action: ec2
                    group="{{ security_group }}"
                    instance_type="{{instance_type }}"
                    keypair="{{ keypair }}"
                    image="{{ imageid }}"
                    wait=true
                    region="{{ region }}"
                    count="{{count}}"
      register: ec2
    
    - name: Wait for EC2 Instance to Spin-up and ready for SSH access
      local_action: wait_for
                    host={{item.public_ip}}
                    port=22
                    state=started
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Name: Ansible Node1
          Owner: ME

            