---
- hosts: all
  vars:
pack_name: tomcat
additional_packages:
- tomcat7-docs
- tomcat7-admin
- tomcat7-examples
  become: yes
  tasks:
  - name: install tomcat server
    package:
      name: "{{ pack_name }}"
      state: present
    notify:
    - restart tomcat
  - name: install tomcat packages
    package:
     name: "{{ item }}"
     state: present
    with_items: "{{ additional_packages }}"
    notify:
    - restart tomcat
    notify:
    - restart tomcat
  handlers:
  - name: restart tomcat
    service:
      name: "{{ pack_name }}"
      enabled: yes
      state: restarted
      