pipeline{
    agent any
    tools{
        maven 'maven_3'
    }
    environment {
    DOCKER_TAG = getVersion()
        }
    stages{
        stage('SCM'){
            steps {
            git 'https://github.com/javahometech/dockeransiblejenkins.git'
        }
        }
        stage ('Maven Build'){
            steps{
                sh 'mvn clean install package'
            }
        }
        stage ('Docker Build'){
            steps{
                sh "docker build -t formycore/hariapp :${DOCKER_TAG} ."
            }
        }

    }
}
def getVersion(){
    def commitHash = sh label:'',returnStdout: true, script: 'git rev-parse --short HEAD'
    retrun commitHash
}