---
- hosts: docker
  become: yes
  tasks:
    - name: create and copy the files
      copy:
        src: /home/ansible/docker/docker.conf/
        dest: etc/systemd/system/docker.service.d/docker.conf
        remote_src: yes
    - name: restart docker deamon
      command: systemctl deamon-reload
    - name: Restarted docker service
      service:
        name: docker
        state: restarted