---
- hosts: localhost
  connection: local
  tasks:
    - name: Creating a security group
      local_action:
        module: ec2_group
        name: aws_grp
        description: Security Group for Newly Created EC2 Instance
        region: us-east-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0


    - name: Lauch the Ec2 Instance
      local_action: ec2
                    group=aws_grp
                    instance_type=t2.micro
                    image=ami-0b500ef59d8335eee
                    region=us-east-2
                    keypair=key
                    count=1
      register: ec2
    - name: Wait for ec2 instance and for ssh access
      local_action: wait_for
                   host={{ item.public_ip}}
                   port=22
                   state=started
      with_items: "{{ ec2.instances }}"
    - name : Adding Tags for Identity
      local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Name: Linux Redhat
          Owner: Linux