---
- hosts: all
  user: ansible
  become: yes
  tasks:
    - name: Create new user
      user:
        name: package
        uid: 1113
        comment: Yogesh Mehta
        password: "{{ user_pass }}"
        shell: /bin/bash
      tags: Create_User
    - name: root password change
      user:
        name=root  update_password=always password="{{root_pass}}"
      tags: Update_root_pass