pipeline{
    agent any
    stages{ 
         stage("Sonar_Qube"){
           agent{
              docker {
                  image 'openjdk:11'
              }
        }
        steps{
            script{
                withSonarQubeEnv(credentialsId: 'sonar_id') {
                sh 'chmod +x gradlew'
                sh './gradlew sonarqube'
                    }
            }
        }
    }
    }
}
