- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc variables
      include_vars: vpc-setup
    - name: Create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    - debug:
        var: vpcout
    
    - name: create Public Subnet1 in Zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        map_public: yes
        tags:
          Name: samantha-pub-sub1
      register: samantha_pubsub1_out
    - debug:
        var: samantha_pubsub1_out
    - name: create public subnet2 in zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        map_public: yes
        tags:
          Name: samantha-pub-sub2
      register: sam_pub2_out
    - debug:
        var: sam_pub2_out
    - name: create public subnet3 in zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        map_public: yes
        tags:
          Name: samantha-pub-sub3
      register: sam_pub3_out
    - debug:
        var: sam_pub3_out
    - name: create private subnet1 in zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        tags:
          Name: samantha-priv-sub1
      register: sam_priv1_out
    - debug:
        var: sam_priv1_out
    - name: create private subnet2 in zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        tags:
          Name: samantha-priv-sub2
      register: sam_priv2_out
    - debug:
        var: sam_priv2_out
    - name: create private subnet3 in zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        tags:
          Name: samantha-priv-sub3
      register: sam_priv3_out
    - debug:
        var: sam_priv3_out



